// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampSleepAwayDB.Migrations
{
    [DbContext(typeof(CampContext))]
    [Migration("20250311130927_seedupdate")]
    partial class seedupdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cabin", b =>
                {
                    b.Property<int>("CabinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CabinId"));

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CabinId");

                    b.ToTable("Cabins");

                    b.HasData(
                        new
                        {
                            CabinId = 1,
                            MaxCapacity = 4,
                            Name = "Cabin 1"
                        },
                        new
                        {
                            CabinId = 2,
                            MaxCapacity = 4,
                            Name = "Cabin 2"
                        },
                        new
                        {
                            CabinId = 3,
                            MaxCapacity = 4,
                            Name = "Cabin 3"
                        });
                });

            modelBuilder.Entity("Camper", b =>
                {
                    b.Property<int>("CamperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CamperId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CamperId");

                    b.ToTable("Campers");

                    b.HasData(
                        new
                        {
                            CamperId = 1,
                            Name = "Camper 1"
                        },
                        new
                        {
                            CamperId = 2,
                            Name = "Camper 2"
                        },
                        new
                        {
                            CamperId = 3,
                            Name = "Camper 3"
                        },
                        new
                        {
                            CamperId = 4,
                            Name = "Camper 4"
                        },
                        new
                        {
                            CamperId = 5,
                            Name = "Camper 5"
                        },
                        new
                        {
                            CamperId = 6,
                            Name = "Camper 6"
                        },
                        new
                        {
                            CamperId = 7,
                            Name = "Camper 7"
                        },
                        new
                        {
                            CamperId = 8,
                            Name = "Camper 8"
                        },
                        new
                        {
                            CamperId = 9,
                            Name = "Camper 9"
                        },
                        new
                        {
                            CamperId = 10,
                            Name = "Camper 10"
                        },
                        new
                        {
                            CamperId = 11,
                            Name = "Camper 11"
                        },
                        new
                        {
                            CamperId = 12,
                            Name = "Camper 12"
                        },
                        new
                        {
                            CamperId = 13,
                            Name = "Camper 13"
                        },
                        new
                        {
                            CamperId = 14,
                            Name = "Camper 14"
                        },
                        new
                        {
                            CamperId = 15,
                            Name = "Camper 15"
                        },
                        new
                        {
                            CamperId = 16,
                            Name = "Camper 16"
                        },
                        new
                        {
                            CamperId = 17,
                            Name = "Camper 17"
                        },
                        new
                        {
                            CamperId = 18,
                            Name = "Camper 18"
                        });
                });

            modelBuilder.Entity("CamperCabinAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinId")
                        .HasColumnType("int");

                    b.Property<int>("CamperId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CabinId");

                    b.HasIndex("CamperId");

                    b.ToTable("CamperCabinAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CabinId = 1,
                            CamperId = 1,
                            EndDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CabinId = 1,
                            CamperId = 2,
                            EndDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CabinId = 1,
                            CamperId = 3,
                            EndDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CabinId = 2,
                            CamperId = 4,
                            EndDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CabinId = 2,
                            CamperId = 5,
                            EndDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CabinId = 2,
                            CamperId = 6,
                            EndDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CabinId = 3,
                            CamperId = 7,
                            EndDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CabinId = 3,
                            CamperId = 8,
                            EndDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CabinId = 3,
                            CamperId = 9,
                            EndDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Counselor", b =>
                {
                    b.Property<int>("CounselorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CounselorId"));

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CounselorId");

                    b.ToTable("Counselors");

                    b.HasData(
                        new
                        {
                            CounselorId = 1,
                            EmploymentDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Counselor 1"
                        },
                        new
                        {
                            CounselorId = 2,
                            EmploymentDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Counselor 2"
                        },
                        new
                        {
                            CounselorId = 3,
                            EmploymentDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Counselor 3"
                        });
                });

            modelBuilder.Entity("CounselorCabinAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinId")
                        .HasColumnType("int");

                    b.Property<int>("CounselorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CabinId");

                    b.HasIndex("CounselorId");

                    b.ToTable("CounselorCabinAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CabinId = 1,
                            CounselorId = 1,
                            EndDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CabinId = 2,
                            CounselorId = 2,
                            EndDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CabinId = 3,
                            CounselorId = 3,
                            EndDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NextOfKin", b =>
                {
                    b.Property<int>("NextOfKinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NextOfKinId"));

                    b.Property<int>("CamperId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NextOfKinId");

                    b.HasIndex("CamperId");

                    b.ToTable("NextOfKins");

                    b.HasData(
                        new
                        {
                            NextOfKinId = 1,
                            CamperId = 1,
                            Name = "NextOfKin 1",
                            Relationship = "Parent"
                        },
                        new
                        {
                            NextOfKinId = 2,
                            CamperId = 2,
                            Name = "NextOfKin 2",
                            Relationship = "Parent"
                        },
                        new
                        {
                            NextOfKinId = 3,
                            CamperId = 3,
                            Name = "NextOfKin 3",
                            Relationship = "Parent"
                        },
                        new
                        {
                            NextOfKinId = 4,
                            CamperId = 4,
                            Name = "NextOfKin 4",
                            Relationship = "Parent"
                        });
                });

            modelBuilder.Entity("CamperCabinAssignment", b =>
                {
                    b.HasOne("Cabin", "Cabin")
                        .WithMany("CamperCabinAssignments")
                        .HasForeignKey("CabinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Camper", "Camper")
                        .WithMany("CamperCabinAssignments")
                        .HasForeignKey("CamperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabin");

                    b.Navigation("Camper");
                });

            modelBuilder.Entity("CounselorCabinAssignment", b =>
                {
                    b.HasOne("Cabin", "Cabin")
                        .WithMany("CounselorCabinAssignments")
                        .HasForeignKey("CabinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Counselor", "Counselor")
                        .WithMany("CounselorCabinAssignments")
                        .HasForeignKey("CounselorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabin");

                    b.Navigation("Counselor");
                });

            modelBuilder.Entity("NextOfKin", b =>
                {
                    b.HasOne("Camper", "Camper")
                        .WithMany("NextOfKins")
                        .HasForeignKey("CamperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camper");
                });

            modelBuilder.Entity("Cabin", b =>
                {
                    b.Navigation("CamperCabinAssignments");

                    b.Navigation("CounselorCabinAssignments");
                });

            modelBuilder.Entity("Camper", b =>
                {
                    b.Navigation("CamperCabinAssignments");

                    b.Navigation("NextOfKins");
                });

            modelBuilder.Entity("Counselor", b =>
                {
                    b.Navigation("CounselorCabinAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
